# Server configuration
server.port=8081
spring.application.name=item-service

# Kafka configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=orderEvent:com.example.events.OrderEvent

# Kafka Consumer
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=orderEvent:com.example.events.OrderEvent

# Kafka Topics
kafka.topics.order-created=order-created-events
kafka.topics.inventory-reserved=inventory-reserved-events